import {
  BookOpen,
  Building2,
  Bus,
  Cake,
  Calendar,
  CalendarDays,
  CalendarRange,
  CheckCircle2,
  ClipboardList,
  Clock,
  FileText,
  FlaskConical,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  Home,
  Hourglass,
  Landmark,
  MessageCircle,
  PenLine,
  Pill,
  Plane,
  RefreshCw,
  Route,
  School,
  Search,
  ShieldAlert,
  Stethoscope,
  Sun,
  Target,
  Users,
  Wallet,
} from 'lucide-react';
import type { IconComponent } from '@/modules/design-system';

export const FEATURE_ICON_MAP: Record<string, IconComponent> = {
  '🏠': Home,
  '🏡': Home,
  '🤝': Handshake,
  '👨‍👩‍👧': Users,
  '👪': Users,
  '🎓': GraduationCap,
  '📋': ClipboardList,
  '📄': FileText,
  '📚': BookOpen,
  '🗣️': MessageCircle,
  '📅': Calendar,
  '🧩': Heart,
  '💰': Wallet,
  '🚌': Bus,
  '📆': CalendarDays,
  '🩺': Stethoscope,
  '🏥': Building2,
  '💊': Pill,
  '🧪': FlaskConical,
  '✈️': Plane,
  '☀️': Sun,
  '🔄': RefreshCw,
  '📝': PenLine,
  '🌏': Globe,
  '📗': BookOpen,
  '📘': BookOpen,
  '📕': BookOpen,
  '🛤️': Route,
  '🎯': Target,
  '🏫': School,
  '✅': CheckCircle2,
  '🔍': Search,
  '🚨': ShieldAlert,
  '🗓️': CalendarRange,
  '🔚': Clock,
  '🎂': Cake,
  '⏳': Hourglass,
  '🏛️': Landmark,
};
