export type ContentStaticRoute =
  | 'about'
  | 'contact'
  | 'privacy'
  | 'terms'
  | 'cookies'
  | 'accessibility'
  | 'safety'
  | 'trust'
  | 'security'
  | 'data-privacy'
  | 'methodology'
  | 'help'
  | 'faq'
  | 'careers'
  | 'press'
  | 'for-families'
  | 'for-agents'
  | 'for-schools'
  | 'request-info'
  | 'admissions-requirements'
  | 'payment-options'
  | 'how-to-apply'
  | 'tuition-fees'
  | 'scholarships'
  | 'international-students'
  | 'agent-resources'
  | 'entry-requirements'
  | 'new-families'
  | 'open-days'
  | 'college-counselling'
  | 'publications';

export interface ContentStaticPageProps {
  params: Promise<{ locale: string }>;
}
