import type { ContentPageSeed } from '@/modules/content-pages/types/content-pages.types';

const contentPageSeedRows = [
  ['admissions-hub-australian-schools', 'admissions', 'admissions', 'families', 'Admissions hub for Australian schools', 'A practical landing page for families comparing application windows, documents, interviews, and next actions.', '/images/auth/parent.jpg', 'brand'],
  ['how-to-apply-year-7', 'admissions', 'admissions', 'families', 'How to apply for Year 7', 'A staged example of enquiry, shortlist, documents, interview, offer, and enrolment acceptance.', '/images/auth/parent.jpg', 'brand'],
  ['application-documents-checklist', 'admissions', 'faq', 'families', 'Application documents checklist', 'A detailed checklist page for passports, reports, English testing, guardianship, and school preferences.', '/images/auth/parent.jpg', 'featured'],
  ['interview-preparation-guide', 'admissions', 'overview', 'families', 'Interview preparation guide', 'A page pattern for student interviews, parent conversations, trial classes, and follow-up notes.', '/images/auth/parent.jpg', 'trust'],
  ['enrolment-decision-timeline', 'admissions', 'events', 'families', 'Enrolment decision timeline', 'A timeline page for submission dates, assessment windows, offer rounds, and acceptance deadlines.', '/images/auth/parent.jpg', 'brand'],
  ['entry-requirements', 'admissions', 'admissions', 'families', 'Entry requirements', 'A requirements page for year level, English evidence, interviews, school reports, references, and application readiness.', '/images/auth/parent.jpg', 'trust'],
  ['admissions-publications', 'admissions', 'directory', 'families', 'Admissions publications and downloads', 'A publication hub for viewbooks, fee sheets, application forms, event guides, and family checklists.', '/images/auth/school.jpg', 'featured'],
  ['school-fees-planning', 'fees', 'fees', 'families', 'School fees planning', 'A tuition planning page with annual fees, one-off charges, optional extras, and billing checkpoints.', '/images/auth/parent.jpg', 'featured'],
  ['tuition-payment-calendar', 'fees', 'fees', 'families', 'Tuition payment calendar', 'A fee calendar example for deposits, term instalments, late fees, refunds, and renewal timing.', '/images/auth/parent.jpg', 'featured'],
  ['scholarships-and-bursaries', 'fees', 'overview', 'families', 'Scholarships and bursaries', 'A funding page pattern for eligibility, deadlines, evidence, interviews, and related fee links.', '/images/auth/parent.jpg', 'trust'],
  ['first-year-costs-checklist', 'fees', 'faq', 'families', 'First-year costs checklist', 'A parent-facing checklist for tuition, uniforms, devices, excursions, insurance, transport, and boarding.', '/images/auth/parent.jpg', 'featured'],
  ['refund-and-withdrawal-policy', 'fees', 'overview', 'families', 'Refund and withdrawal policy', 'A policy-style page that links fee rules to enrolment dates and family support contacts.', '/images/auth/parent.jpg', 'muted'],
  ['international-family-start-here', 'international', 'international', 'families', 'International family start here', 'A starting point for families moving from overseas and comparing school options in Australia.', '/images/auth/parent.jpg', 'brand'],
  ['student-visa-overview', 'international', 'international', 'families', 'Student visa overview', 'A visa support page linking school offers, guardian planning, health cover, and document checks.', '/images/auth/parent.jpg', 'trust'],
  ['english-test-pathways', 'international', 'curriculum', 'families', 'English test pathways', 'An English entry page covering AEAS, IELTS, EAL support, bridging programs, and retest timing.', '/images/auth/parent.jpg', 'trust'],
  ['relocation-and-arrival', 'international', 'international', 'families', 'Relocation and arrival', 'A relocation page for airport arrival, local setup, orientation, uniforms, devices, and first week support.', '/images/auth/parent.jpg', 'brand'],
  ['new-family-transitions', 'international', 'international', 'families', 'New family transitions', 'A transition page for orientation, buddies, communication rhythms, parent onboarding, and first-month support.', '/images/auth/parent.jpg', 'trust'],
  ['health-cover-and-wellbeing', 'international', 'student-life', 'families', 'Health cover and wellbeing', 'A support page connecting overseas health cover, counselling, wellbeing teams, and emergency contacts.', '/images/auth/parent.jpg', 'trust'],
  ['australian-curriculum-overview', 'curriculum', 'curriculum', 'families', 'Australian curriculum overview', 'A curriculum explainer for families comparing learning stages, subjects, assessment, and outcomes.', '/images/auth/school.jpg', 'brand'],
  ['ib-programme-pathways', 'curriculum', 'curriculum', 'families', 'IB programme pathways', 'A framework page for PYP, MYP, Diploma pathways, school fit, assessment style, and subject choice.', '/images/auth/school.jpg', 'trust'],
  ['stem-subject-selection', 'curriculum', 'curriculum', 'families', 'STEM subject selection', 'A subject detail page showing prerequisites, extension options, clubs, competitions, and future pathways.', '/images/auth/school.jpg', 'featured'],
  ['arts-sport-co-curricular', 'curriculum', 'student-life', 'families', 'Arts, sport, and co-curricular', 'A page type for programs beyond class: performing arts, sport, leadership, service, and competitions.', '/images/auth/school.jpg', 'featured'],
  ['english-language-support', 'curriculum', 'curriculum', 'families', 'English language support', 'A support page pattern for EAL assessment, classroom scaffolding, tutoring, and parent reporting.', '/images/auth/school.jpg', 'trust'],
  ['student-life-overview', 'student-life', 'student-life', 'families', 'Student life overview', 'A hub page for community, clubs, wellbeing, meals, transport, uniforms, and everyday student routines.', '/images/auth/parent.jpg', 'brand'],
  ['clubs-and-activities', 'student-life', 'student-life', 'families', 'Clubs and activities', 'A directory-style page for sport, arts, STEM clubs, service, language groups, and leadership programs.', '/images/auth/school.jpg', 'featured'],
  ['wellbeing-support', 'student-life', 'student-life', 'families', 'Wellbeing support', 'A school support page for counselling, pastoral care, health services, peer support, and family escalation paths.', '/images/auth/parent.jpg', 'trust'],
  ['uniforms-transport-and-meals', 'student-life', 'faq', 'families', 'Uniforms, transport, and meals', 'A practical family FAQ page covering daily logistics before the first day of school.', '/images/auth/parent.jpg', 'muted'],
  ['parent-community', 'student-life', 'overview', 'families', 'Parent community', 'A community page for parent groups, school events, volunteering, translations, and communication rhythms.', '/images/auth/parent.jpg', 'trust'],
  ['boarding-school-overview', 'boarding', 'boarding', 'families', 'Boarding school overview', 'A boarding hub covering routines, supervision, weekend activities, facilities, and academic support.', '/images/auth/school.jpg', 'brand'],
  ['homestay-vs-boarding', 'boarding', 'boarding', 'families', 'Homestay vs boarding', 'A comparison page for families choosing between residential boarding, homestay, and guardian arrangements.', '/images/auth/school.jpg', 'featured'],
  ['weekend-life-for-boarders', 'boarding', 'student-life', 'families', 'Weekend life for boarders', 'A student-life page pattern for weekend programs, sport, study sessions, outings, and wellbeing checks.', '/images/auth/school.jpg', 'trust'],
  ['boarding-application-process', 'boarding', 'admissions', 'families', 'Boarding application process', 'A boarding admissions page for eligibility, interviews, medical forms, guardian rules, and offers.', '/images/auth/school.jpg', 'brand'],
  ['accommodation-safety', 'boarding', 'faq', 'families', 'Accommodation safety', 'A safety and policy page for supervision, emergency contacts, leave approvals, visitors, and pastoral care.', '/images/auth/school.jpg', 'muted'],
  ['agent-partner-overview', 'agents', 'agents', 'agents', 'Agent partner overview', 'A partner landing page for education agents supporting families through search, shortlist, and admissions.', '/images/auth/agent.jpg', 'brand'],
  ['authorised-agent-directory', 'agents', 'directory', 'agents', 'Authorised agent directory', 'A directory page pattern for country coverage, specialisms, compliance status, and school matching support.', '/images/auth/agent.jpg', 'trust'],
  ['agent-training-resources', 'agents', 'agents', 'agents', 'Agent training resources', 'A resource page for onboarding, school data literacy, application standards, and family communication.', '/images/auth/agent.jpg', 'featured'],
  ['student-application-pipeline', 'agents', 'agents', 'agents', 'Student application pipeline', 'A workflow page for managing leads, shortlists, documents, messages, and school responses.', '/images/auth/agent.jpg', 'brand'],
  ['compliance-for-agents', 'agents', 'faq', 'agents', 'Compliance for agents', 'A compliance FAQ page covering consent, disclosure, document handling, and communication standards.', '/images/auth/agent.jpg', 'muted'],
  ['school-profile-claiming', 'schools', 'schools', 'schools', 'School profile claiming', 'A school-facing page showing how teams claim and improve their SchoolGo profile.', '/images/auth/school.jpg', 'brand'],
  ['admissions-team-workflow', 'schools', 'schools', 'schools', 'Admissions team workflow', 'A workflow page for enquiries, shortlist signals, applications, messages, and offer follow-up.', '/images/auth/school.jpg', 'trust'],
  ['international-student-growth', 'schools', 'schools', 'schools', 'International student growth', 'A school growth page for visibility, data quality, markets, trust badges, and enquiry conversion.', '/images/auth/school.jpg', 'featured'],
  ['school-pricing-plan', 'schools', 'fees', 'schools', 'School pricing plan', 'A pricing page pattern for listing packages, admissions tools, profile enhancements, and annual planning.', '/images/auth/school.jpg', 'featured'],
  ['school-data-quality', 'schools', 'faq', 'schools', 'School data quality', 'A data standards page for campuses, fees, CRICOS details, curriculum, boarding, and enrolment status.', '/images/auth/school.jpg', 'muted'],
  ['high-school-to-university', 'pathways', 'curriculum', 'families', 'High school to university', 'A pathway page linking subject selection, senior certificates, prerequisites, careers, and university entry.', '/images/auth/school.jpg', 'brand'],
  ['career-counselling-roadmap', 'pathways', 'overview', 'families', 'Career counselling roadmap', 'A counselling page for year-by-year planning, workshops, interviews, applications, and outcomes.', '/images/auth/school.jpg', 'trust'],
  ['subject-prerequisites', 'pathways', 'directory', 'families', 'Subject prerequisites', 'A directory-style page linking subjects, future degrees, entry assumptions, and school support services.', '/images/auth/school.jpg', 'featured'],
  ['exam-and-assessment-calendar', 'pathways', 'events', 'families', 'Exam and assessment calendar', 'A calendar page pattern for exams, reports, counselling checkpoints, and application milestones.', '/images/auth/school.jpg', 'brand'],
  ['graduate-outcomes', 'pathways', 'overview', 'families', 'Graduate outcomes', 'A proof page for destinations, skills, alumni stories, university offers, and career confidence.', '/images/auth/school.jpg', 'trust'],
  ['open-day-calendar', 'events', 'events', 'families', 'Open day calendar', 'An event listing page for tours, open mornings, principal briefings, and application clinics.', '/images/auth/school.jpg', 'brand'],
  ['campus-tour-planning', 'events', 'events', 'families', 'Campus tour planning', 'A visit page for tour formats, campus maps, divisions, family questions, accessibility notes, and follow-up actions.', '/images/auth/school.jpg', 'brand'],
  ['virtual-school-tours', 'events', 'events', 'families', 'Virtual school tours', 'A virtual visit page for online tours, campus maps, learning spaces, boarding houses, and Q&A.', '/images/auth/school.jpg', 'featured'],
  ['admissions-webinars', 'events', 'events', 'families', 'Admissions webinars', 'A webinar page for family briefings, visa sessions, school comparisons, and agent co-hosted events.', '/images/auth/agent.jpg', 'trust'],
  ['orientation-week', 'events', 'events', 'families', 'Orientation week', 'A new-student page for first-week events, buddy programs, parent sessions, and school systems.', '/images/auth/parent.jpg', 'brand'],
  ['regional-family-briefings', 'events', 'events', 'families', 'Regional family briefings', 'A regional event page for market-specific school advice and multilingual family sessions.', '/images/auth/agent.jpg', 'featured'],
  ['about-schoolgo', 'company', 'overview', 'all', 'About SchoolGo', 'A company page explaining SchoolGo’s role in school discovery, comparison, admissions readiness, and trust.', '/images/auth/parent.jpg', 'brand'],
  ['contact-admissions-team', 'company', 'directory', 'all', 'Contact the SchoolGo team', 'A contact page pattern routing families, agents, and schools to the right next step.', '/images/auth/agent.jpg', 'trust'],
  ['schoolgo-data-methodology', 'company', 'faq', 'all', 'SchoolGo data methodology', 'A trust page describing how school data, fees, CRICOS details, and profile updates are handled.', '/images/auth/school.jpg', 'muted'],
  ['privacy-and-safety', 'company', 'faq', 'all', 'Privacy and safety', 'A policy-style page for account safety, consent, document handling, and responsible school communication.', '/images/auth/parent.jpg', 'muted'],
  ['partner-network', 'company', 'directory', 'all', 'SchoolGo partner network', 'A network page for schools, agents, family support partners, relocation specialists, and events.', '/images/auth/agent.jpg', 'featured'],
  ['compare-schools-guide', 'school-search', 'directory', 'families', 'Compare schools guide', 'A comparison page for fees, location, curriculum, boarding, English support, and enrolment availability.', '/images/auth/parent.jpg', 'brand'],
  ['choose-school-by-location', 'school-search', 'directory', 'families', 'Choose a school by location', 'A location page for suburbs, transport, homestay options, commute time, and school clusters.', '/images/auth/parent.jpg', 'trust'],
  ['religious-and-independent-schools', 'school-search', 'directory', 'families', 'Religious and independent schools', 'A sector explainer comparing school identity, governance, values, fees, and admissions fit.', '/images/auth/school.jpg', 'featured'],
  ['selective-and-specialist-programs', 'school-search', 'directory', 'families', 'Selective and specialist programs', 'A program page for selective entry, music, sport, STEM, languages, and portfolio requirements.', '/images/auth/school.jpg', 'brand'],
  ['cricos-and-enrolment-status', 'school-search', 'faq', 'families', 'CRICOS and enrolment status', 'A search support page explaining CRICOS registration, availability signals, and international enrolment rules.', '/images/auth/school.jpg', 'muted'],
  ['privacy-policy', 'company', 'faq', 'all', 'Privacy policy', 'A replaceable privacy page covering website data, account data, school data, analytics, retention, and contact paths.', '/images/auth/parent.jpg', 'muted'],
  ['terms-of-service', 'company', 'faq', 'all', 'Terms of service', 'A replaceable terms page for acceptable use, accounts, school data, content ownership, liability, and service changes.', '/images/auth/school.jpg', 'muted'],
  ['cookie-policy', 'company', 'faq', 'all', 'Cookie policy', 'A plain-language cookie page for analytics, consent, preference controls, essential cookies, and updates.', '/images/auth/parent.jpg', 'muted'],
  ['accessibility-statement', 'company', 'overview', 'all', 'Accessibility statement', 'A public commitment page for keyboard access, contrast, assistive technology, feedback, and remediation workflow.', '/images/auth/parent.jpg', 'trust'],
  ['safety-and-trust', 'company', 'overview', 'all', 'Safety and trust', 'A trust center page for families, agents, and schools covering safeguards, escalation, consent, and responsible communication.', '/images/auth/school.jpg', 'trust'],
  ['trust-and-safety-center', 'company', 'overview', 'all', 'Trust and safety center', 'A hub page for privacy, security, moderation, student protection, data quality, and support responsibilities.', '/images/auth/school.jpg', 'brand'],
  ['security-center', 'company', 'overview', 'all', 'Security center', 'A security overview for access control, infrastructure, monitoring, incident response, vendor review, and operational ownership.', '/images/auth/school.jpg', 'trust'],
  ['data-privacy-center', 'company', 'faq', 'all', 'Data privacy center', 'A data transparency hub for what SchoolGo collects, what it does not collect, retention, analytics, and school data ownership.', '/images/auth/school.jpg', 'trust'],
  ['help-center', 'company', 'directory', 'all', 'Help center', 'A support directory for family questions, school profile edits, agent workflows, search help, billing questions, and account access.', '/images/auth/agent.jpg', 'featured'],
  ['schoolgo-faq', 'company', 'faq', 'all', 'SchoolGo FAQ', 'A public FAQ page for common questions about school search, admissions content, fees, data quality, and profile ownership.', '/images/auth/parent.jpg', 'featured'],
  ['careers-at-schoolgo', 'company', 'overview', 'all', 'Careers at SchoolGo', 'A lightweight careers page for mission, teams, hiring principles, open roles, and candidate contact.', '/images/auth/agent.jpg', 'brand'],
  ['media-room', 'company', 'directory', 'all', 'Media room', 'A press and media page for company summary, boilerplate, logos, leadership contacts, and story angles.', '/images/auth/school.jpg', 'featured'],
  ['family-guide-start', 'school-search', 'overview', 'families', 'For families', 'A family landing page for search, shortlist, admissions readiness, fees, international support, and next-step routing.', '/images/auth/parent.jpg', 'brand'],
  ['request-information', 'admissions', 'admissions', 'families', 'Request information', 'A conversion page for families to ask about schools, fees, documents, availability, and admissions timing.', '/images/auth/parent.jpg', 'brand'],
  ['application-requirements', 'admissions', 'admissions', 'families', 'Application requirements', 'A requirements page for reports, identity documents, English evidence, recommendations, interviews, and offer acceptance.', '/images/auth/parent.jpg', 'trust'],
  ['payment-options', 'fees', 'fees', 'families', 'Payment options', 'A tuition payment page for deposits, instalments, refunds, late fees, payment channels, and family finance planning.', '/images/auth/parent.jpg', 'featured'],
] as const;

export const contentPageSeeds = contentPageSeedRows.map(
  ([slug, category, type, audience, title, subtitle, image, accent]) => ({
    slug,
    category,
    type,
    audience,
    title,
    subtitle,
    image,
    accent,
  }),
) satisfies ContentPageSeed[];
