import type { ContentPageDesign } from '@/modules/content-blocks/types/content-blocks.types';

export const contentPageDesigns = [
  { slug: 'admissions-hub', name: 'Admissions Hub', description: 'A route-map page with CTAs, timeline, checklist, and related pages.', useCase: 'Admissions landing pages', samplePageSlug: 'admissions-hub-australian-schools', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'anchorPillNav', 'metricStrip', 'audienceCards', 'processStepper', 'deadlineTimeline', 'checklistRows', 'relatedPages', 'ctaBanner'] },
  { slug: 'application-guide', name: 'Application Guide', description: 'A process-heavy article page for families preparing documents and interviews.', useCase: 'How-to guides', samplePageSlug: 'how-to-apply-year-7', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'keyFactRows', 'approvalFlow', 'evidencePack', 'riskRegister', 'resourceRows', 'faqRows', 'ctaBanner'] },
  { slug: 'fee-planner', name: 'Fee Planner', description: 'A finance page with cost summary, matrix, resource rows, and FAQs.', useCase: 'Fees and tuition pages', samplePageSlug: 'school-fees-planning', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'kpiDashboard', 'feeSummary', 'governanceMatrix', 'comparisonMatrix', 'serviceLevel', 'resourceRows', 'ctaBanner'] },
  { slug: 'scholarship-overview', name: 'Scholarship Overview', description: 'A benefits page using proof, story, steps, and resource links.', useCase: 'Funding pages', samplePageSlug: 'scholarships-and-bursaries', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'metricStrip', 'storyPreview', 'processStepper', 'faqRows', 'resourceRows', 'ctaBanner'] },
  { slug: 'international-start', name: 'International Start', description: 'A family orientation page with audience routing and trust markers.', useCase: 'International family hubs', samplePageSlug: 'international-family-start-here', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'heroMedia', 'trustBadgeRow', 'featureTileGrid', 'checklistRows', 'contactRouting', 'relatedPages'] },
  { slug: 'visa-support', name: 'Visa Support', description: 'A support page with key facts, checklist, FAQs, and links.', useCase: 'Visa and compliance pages', samplePageSlug: 'student-visa-overview', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'keyFactRows', 'checklistRows', 'resourceRows', 'faqRows', 'linkRail', 'ctaBanner'] },
  { slug: 'curriculum-pathway', name: 'Curriculum Pathway', description: 'A pathway page with program cards, features, story, and related links.', useCase: 'Curriculum pages', samplePageSlug: 'australian-curriculum-overview', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'programCards', 'featureTileGrid', 'imageText', 'linkRail', 'relatedPages'] },
  { slug: 'ib-program', name: 'IB Program', description: 'A program detail page with media, facts, timeline, and FAQs.', useCase: 'Program detail pages', samplePageSlug: 'ib-programme-pathways', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'heroMedia', 'keyFactRows', 'deadlineTimeline', 'faqRows', 'ctaBanner'] },
  { slug: 'student-life-hub', name: 'Student Life Hub', description: 'A warm hub page using stories, features, programs, and related content.', useCase: 'Student life pages', samplePageSlug: 'student-life-overview', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'storyPreview', 'featureTileGrid', 'programCards', 'quoteBand', 'relatedPages', 'ctaBanner'] },
  { slug: 'wellbeing-support', name: 'Wellbeing Support', description: 'A support-service page with trust markers and contact routing.', useCase: 'Wellbeing pages', samplePageSlug: 'wellbeing-support', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'trustBadgeRow', 'featureTileGrid', 'checklistRows', 'contactRouting', 'faqRows'] },
  { slug: 'boarding-overview', name: 'Boarding Overview', description: 'A residential-life page with image, comparison, checklist, and timeline.', useCase: 'Boarding pages', samplePageSlug: 'boarding-school-overview', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'heroMedia', 'comparisonMatrix', 'checklistRows', 'deadlineTimeline', 'relatedPages'] },
  { slug: 'homestay-comparison', name: 'Homestay Comparison', description: 'A decision page centered around tradeoffs and follow-up links.', useCase: 'Comparison pages', samplePageSlug: 'homestay-vs-boarding', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'comparisonMatrix', 'feeSummary', 'faqRows', 'linkRail', 'ctaBanner'] },
  { slug: 'agent-partner', name: 'Agent Partner', description: 'A partner page with audience cards, pipeline steps, resources, and trust.', useCase: 'Agent pages', samplePageSlug: 'agent-partner-overview', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'segmentStrategy', 'operatingModel', 'workflowBoard', 'resourceRows', 'trustBadgeRow', 'ctaBanner'] },
  { slug: 'agent-directory', name: 'Agent Directory', description: 'A directory-style page using program cards, links, and contact routing.', useCase: 'Agent directories', samplePageSlug: 'authorised-agent-directory', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'keyFactRows', 'programCards', 'linkRail', 'contactRouting', 'relatedPages'] },
  { slug: 'school-growth', name: 'School Growth', description: 'A school-facing page with proof, features, story, and CTA.', useCase: 'School marketing pages', samplePageSlug: 'international-student-growth', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'kpiDashboard', 'segmentStrategy', 'integrationMap', 'featureTileGrid', 'storyPreview', 'ctaBanner'] },
  { slug: 'school-pricing', name: 'School Pricing', description: 'A pricing page using fee summary, matrix, FAQs, and links.', useCase: 'School pricing pages', samplePageSlug: 'school-pricing-plan', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'feeSummary', 'comparisonMatrix', 'faqRows', 'resourceRows', 'ctaBanner'] },
  { slug: 'open-day', name: 'Open Day', description: 'An event page with media, timeline, checklist, and final action.', useCase: 'Event pages', samplePageSlug: 'open-day-calendar', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'heroMedia', 'deadlineTimeline', 'checklistRows', 'contactRouting', 'ctaBanner'] },
  { slug: 'virtual-tour', name: 'Virtual Tour', description: 'A media-first page with story preview and feature tiles.', useCase: 'Virtual visit pages', samplePageSlug: 'virtual-school-tours', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'heroMedia', 'storyPreview', 'featureTileGrid', 'linkRail', 'relatedPages'] },
  { slug: 'company-about', name: 'Company About', description: 'A company page with trust, story, audiences, and links.', useCase: 'Company pages', samplePageSlug: 'about-schoolgo', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'metricStrip', 'governanceMatrix', 'riskRegister', 'storyPreview', 'audienceCards', 'contactRouting'] },
  { slug: 'search-explainer', name: 'Search Explainer', description: 'A tool education page with comparison, features, and related pages.', useCase: 'Tool explainer pages', samplePageSlug: 'compare-schools-guide', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'anchorPillNav', 'kpiDashboard', 'comparisonMatrix', 'integrationMap', 'featureTileGrid', 'relatedPages', 'ctaBanner'] },
  { slug: 'enterprise-admissions-ops', name: 'Enterprise Admissions Ops', description: 'A workflow-heavy admissions operations page with gates, risks, evidence, and SLAs.', useCase: 'Admissions operations', samplePageSlug: 'admissions-team-workflow', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'kpiDashboard', 'operatingModel', 'workflowBoard', 'approvalFlow', 'riskRegister', 'serviceLevel', 'ctaBanner'] },
  { slug: 'enterprise-agent-portal', name: 'Enterprise Agent Portal', description: 'A partner operations design for agent enablement, compliance, and pipeline visibility.', useCase: 'Agent enablement', samplePageSlug: 'student-application-pipeline', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'segmentStrategy', 'workflowBoard', 'governanceMatrix', 'evidencePack', 'integrationMap', 'resourceRows', 'ctaBanner'] },
  { slug: 'enterprise-school-growth', name: 'Enterprise School Growth', description: 'A school-facing executive page for demand signals, controls, integrations, and outcomes.', useCase: 'School growth operations', samplePageSlug: 'school-profile-claiming', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'kpiDashboard', 'segmentStrategy', 'integrationMap', 'governanceMatrix', 'serviceLevel', 'relatedPages'] },
  { slug: 'enterprise-compliance-center', name: 'Enterprise Compliance Center', description: 'A control-room page for data methodology, privacy, evidence, and escalation ownership.', useCase: 'Compliance and trust pages', samplePageSlug: 'schoolgo-data-methodology', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'governanceMatrix', 'riskRegister', 'evidencePack', 'approvalFlow', 'faqRows', 'contactRouting'] },
  { slug: 'enterprise-event-operations', name: 'Enterprise Event Operations', description: 'An operations page for open days, webinars, regional briefings, and post-event follow-up.', useCase: 'Event operations', samplePageSlug: 'open-day-calendar', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'kpiDashboard', 'workflowBoard', 'deadlineTimeline', 'serviceLevel', 'contactRouting', 'ctaBanner'] },
  { slug: 'enterprise-international-readiness', name: 'Enterprise International Readiness', description: 'A readiness dashboard for visa, English, relocation, health, and arrival controls.', useCase: 'International family operations', samplePageSlug: 'international-family-start-here', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'kpiDashboard', 'approvalFlow', 'evidencePack', 'riskRegister', 'relatedPages', 'ctaBanner'] },
  { slug: 'enterprise-search-intelligence', name: 'Enterprise Search Intelligence', description: 'A decision-support page for search behavior, comparison criteria, sectors, and enrolment signals.', useCase: 'Search intelligence pages', samplePageSlug: 'compare-schools-guide', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'kpiDashboard', 'segmentStrategy', 'comparisonMatrix', 'integrationMap', 'resourceRows', 'relatedPages'] },
  { slug: 'enterprise-finance-governance', name: 'Enterprise Finance Governance', description: 'A finance operations page for fee controls, refund policy, scholarships, and family readiness.', useCase: 'Finance governance pages', samplePageSlug: 'school-fees-planning', blocks: ['breadcrumbTrail', 'heroIntro', 'answerPanel', 'feeSummary', 'governanceMatrix', 'riskRegister', 'serviceLevel', 'faqRows', 'ctaBanner'] },
] satisfies ContentPageDesign[];

export const contentPageDesignSlugs = contentPageDesigns.map((design) => design.slug);
