export { ParentsHero } from '@/modules/parents-landing/components/ParentsHero';
export { ParentsStatsBar } from '@/modules/parents-landing/components/ParentsStatsBar';
export { ParentsFourSteps } from '@/modules/parents-landing/components/ParentsFourSteps';
export { ParentsAgents } from '@/modules/parents-landing/components/ParentsAgents';
export { ParentsAgentCta } from '@/modules/parents-landing/components/ParentsAgentCta';
export { ParentsAgentHelp } from '@/modules/parents-landing/components/ParentsAgentHelp';
export { ParentsComparison } from '@/modules/parents-landing/components/ParentsComparison';
export { ParentsPickATest } from '@/modules/parents-landing/components/ParentsPickATest';
export { ParentsSevenLanguages } from '@/modules/parents-landing/components/ParentsSevenLanguages';
export { ParentsArticles } from '@/modules/parents-landing/components/ParentsArticles';
export { ParentsTrustBar } from '@/modules/parents-landing/components/ParentsTrustBar';
export { ParentsFaq } from '@/modules/parents-landing/components/ParentsFaq';
export { FaqAccordion } from '@/modules/parents-landing/components/FaqAccordion';
export { ParentsFinalCta } from '@/modules/parents-landing/components/ParentsFinalCta';
export type { FaqItem, FaqAccordionProps, StepData, ParentsFourStepsClientProps, ParentsHeroSearchProps } from '@/modules/parents-landing/types/parents-landing.types';
export type { SchoolPhotoOrLogoProps, ComparisonCell, ComparisonRow, ComparisonSchoolCardsProps, ComparisonDesktopTableProps, ComparisonMobileTableProps } from '@/modules/parents-landing/types/parents-comparison.types';
