import type { SchoolHit } from '@/modules/school-search/types/search-api.types';

export const MOCK_SCHOOL_HITS: SchoolHit[] = [
  {
    documentId: 'mock-001',
    name: 'Melbourne Grammar School',
    slug: 'melbourne-grammar-school',
    state: 'VIC',
    suburb: 'South Yarra',
    postcode: '3141',
    schoolType: 'secondary',
    sector: 'non-government',
    gender: 'boys',
    logoUrl: '/images/placeholders/school-1.jpg',
    lowestAnnualTuition: 38000,
    highestAnnualTuition: 42000,
    scholarshipAvailable: true,
    boardingAvailable: true,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: true,
    totalEnrolment: 1800,
    internationalStudentPercentage: 12,
    religiousAffiliation: 'anglican',
    curriculumOffered: 'VCE',
    levelsOffered: 'secondary',
    yearLevelBands: ['secondary'],
    capacityBands: ['large'],
    _geo: { lat: -37.8396, lng: 144.9830 },
    enrolmentStatus: 'open',
    curriculumCodes: ['VCE', 'IB'],
    accommodation: 'boarding',
    annualTuitionFrom: 38000,
    programTypes: ['australian-cert', 'ib'],
    entryTerms: ['term1', 'term3'],
    atarAvailable: true,
    englishLanguageSupport: true,
    englishTestMinScores: { ielts: 5.5, pte: 50 },
  },
  {
    documentId: 'mock-002',
    name: 'Sydney Grammar School',
    slug: 'sydney-grammar-school',
    state: 'NSW',
    suburb: 'Darlinghurst',
    postcode: '2010',
    schoolType: 'secondary',
    sector: 'non-government',
    gender: 'boys',
    logoUrl: '/images/placeholders/school-2.jpg',
    lowestAnnualTuition: 41000,
    highestAnnualTuition: 45000,
    scholarshipAvailable: true,
    boardingAvailable: false,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: true,
    totalEnrolment: 2100,
    internationalStudentPercentage: 8,
    religiousAffiliation: 'non-denominational',
    curriculumOffered: 'HSC',
    levelsOffered: 'secondary',
    yearLevelBands: ['secondary'],
    capacityBands: ['large'],
    _geo: { lat: -33.8792, lng: 151.2149 },
    enrolmentStatus: 'limited',
    curriculumCodes: ['HSC'],
    accommodation: 'none',
    annualTuitionFrom: 41000,
    programTypes: ['australian-cert'],
    entryTerms: ['term1'],
    atarAvailable: true,
    englishLanguageSupport: false,
    englishTestMinScores: { ielts: 6.0 },
  },
  {
    documentId: 'mock-003',
    name: 'Brisbane Grammar School',
    slug: 'brisbane-grammar-school',
    state: 'QLD',
    suburb: 'Spring Hill',
    postcode: '4000',
    schoolType: 'secondary',
    sector: 'non-government',
    gender: 'boys',
    logoUrl: '/images/placeholders/school-3.jpg',
    lowestAnnualTuition: 24000,
    highestAnnualTuition: 28000,
    scholarshipAvailable: true,
    boardingAvailable: true,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: true,
    totalEnrolment: 1450,
    internationalStudentPercentage: 15,
    religiousAffiliation: 'anglican',
    curriculumOffered: 'QCE',
    levelsOffered: 'secondary',
    yearLevelBands: ['secondary'],
    capacityBands: ['large'],
    _geo: { lat: -27.4601, lng: 153.0253 },
    enrolmentStatus: 'open',
    curriculumCodes: ['QCE', 'IB'],
    accommodation: 'boarding',
    annualTuitionFrom: 24000,
    programTypes: ['australian-cert', 'ib'],
    entryTerms: ['term1', 'term2', 'term3'],
    atarAvailable: true,
    englishLanguageSupport: true,
    englishTestMinScores: { ielts: 5.5, duolingo: 95 },
  },
  {
    documentId: 'mock-004',
    name: 'St Peters College',
    slug: 'st-peters-college',
    state: 'SA',
    suburb: 'Hackney',
    postcode: '5069',
    schoolType: 'secondary',
    sector: 'non-government',
    gender: 'boys',
    logoUrl: '/images/placeholders/school-4.jpg',
    lowestAnnualTuition: 22000,
    highestAnnualTuition: 26000,
    scholarshipAvailable: false,
    boardingAvailable: true,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: false,
    totalEnrolment: 1200,
    internationalStudentPercentage: 18,
    religiousAffiliation: 'anglican',
    curriculumOffered: 'SACE',
    levelsOffered: 'secondary',
    yearLevelBands: ['secondary'],
    capacityBands: ['medium'],
    _geo: { lat: -34.9120, lng: 138.6213 },
    enrolmentStatus: 'waitlist',
    curriculumCodes: ['SACE'],
    accommodation: 'boarding',
    annualTuitionFrom: 22000,
    programTypes: ['australian-cert'],
    entryTerms: ['term1'],
    atarAvailable: true,
    englishLanguageSupport: true,
    englishTestMinScores: { ielts: 5.5, pte: 46 },
  },
  {
    documentId: 'mock-005',
    name: 'Hale School',
    slug: 'hale-school',
    state: 'WA',
    suburb: 'Wembley Downs',
    postcode: '6019',
    schoolType: 'combined',
    sector: 'non-government',
    gender: 'boys',
    logoUrl: '/images/placeholders/school-5.jpg',
    lowestAnnualTuition: 19000,
    highestAnnualTuition: 23000,
    scholarshipAvailable: true,
    boardingAvailable: true,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: true,
    totalEnrolment: 1600,
    internationalStudentPercentage: 10,
    religiousAffiliation: 'anglican',
    curriculumOffered: 'WACE',
    levelsOffered: 'combined',
    yearLevelBands: ['primary', 'secondary'],
    capacityBands: ['large'],
    _geo: { lat: -31.8878, lng: 115.7844 },
    enrolmentStatus: 'open',
    curriculumCodes: ['WACE'],
    accommodation: 'both',
    annualTuitionFrom: 19000,
    programTypes: ['australian-cert'],
    entryTerms: ['term1', 'term2'],
    atarAvailable: true,
    englishLanguageSupport: true,
    englishTestMinScores: { ielts: 5.5, cambridge: 162 },
  },
  {
    documentId: 'mock-006',
    name: 'The Friends School',
    slug: 'the-friends-school',
    state: 'TAS',
    suburb: 'North Hobart',
    postcode: '7000',
    schoolType: 'combined',
    sector: 'non-government',
    gender: 'co-ed',
    logoUrl: '/images/placeholders/school-6.jpg',
    lowestAnnualTuition: 14000,
    highestAnnualTuition: 18000,
    scholarshipAvailable: false,
    boardingAvailable: true,
    hasActiveApplicationTemplate: false,
    hasOpenCapacity: true,
    totalEnrolment: 900,
    internationalStudentPercentage: 6,
    religiousAffiliation: 'quaker',
    curriculumOffered: 'TCE',
    levelsOffered: 'combined',
    yearLevelBands: ['primary', 'secondary'],
    capacityBands: ['medium'],
    _geo: { lat: -42.8746, lng: 147.3199 },
    enrolmentStatus: 'open',
    curriculumCodes: ['TCE', 'IB'],
    accommodation: 'boarding',
    annualTuitionFrom: 14000,
    programTypes: ['australian-cert', 'ib'],
    entryTerms: ['term1', 'term3'],
    atarAvailable: false,
    englishLanguageSupport: true,
    englishTestMinScores: { ielts: 5.0, duolingo: 85 },
  },
  {
    documentId: 'mock-007',
    name: 'Darwin High School',
    slug: 'darwin-high-school',
    state: 'NT',
    suburb: 'Parap',
    postcode: '0820',
    schoolType: 'secondary',
    sector: 'government',
    gender: 'co-ed',
    logoUrl: '/images/placeholders/school-7.jpg',
    lowestAnnualTuition: 0,
    highestAnnualTuition: 0,
    scholarshipAvailable: false,
    boardingAvailable: false,
    hasActiveApplicationTemplate: false,
    hasOpenCapacity: true,
    totalEnrolment: 750,
    internationalStudentPercentage: 3,
    religiousAffiliation: null,
    curriculumOffered: 'NTCET',
    levelsOffered: 'secondary',
    yearLevelBands: ['secondary'],
    capacityBands: ['medium'],
    _geo: { lat: -12.4072, lng: 130.8718 },
    enrolmentStatus: 'open',
    curriculumCodes: ['NTCET'],
    accommodation: 'none',
    annualTuitionFrom: 5000,
    programTypes: ['australian-cert'],
    entryTerms: ['term1', 'term2', 'term3', 'term4'],
    atarAvailable: false,
    englishLanguageSupport: true,
    englishTestMinScores: {},
  },
  {
    documentId: 'mock-008',
    name: 'Canberra Grammar School',
    slug: 'canberra-grammar-school',
    state: 'ACT',
    suburb: 'Red Hill',
    postcode: '2603',
    schoolType: 'combined',
    sector: 'non-government',
    gender: 'co-ed',
    logoUrl: '/images/placeholders/school-8.jpg',
    lowestAnnualTuition: 26000,
    highestAnnualTuition: 30000,
    scholarshipAvailable: true,
    boardingAvailable: true,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: true,
    totalEnrolment: 1300,
    internationalStudentPercentage: 14,
    religiousAffiliation: 'anglican',
    curriculumOffered: 'BSSS',
    levelsOffered: 'combined',
    yearLevelBands: ['primary', 'secondary'],
    capacityBands: ['large'],
    _geo: { lat: -35.3347, lng: 149.1239 },
    enrolmentStatus: 'open',
    curriculumCodes: ['BSSS', 'IB'],
    accommodation: 'boarding',
    annualTuitionFrom: 26000,
    programTypes: ['australian-cert', 'ib'],
    entryTerms: ['term1'],
    atarAvailable: true,
    englishLanguageSupport: true,
    englishTestMinScores: { ielts: 5.5, pte: 46, cambridge: 162 },
  },
  {
    documentId: 'mock-009',
    name: 'MacRobertson Girls High School',
    slug: 'macrobertson-girls-high-school',
    state: 'VIC',
    suburb: 'Melbourne',
    postcode: '3004',
    schoolType: 'secondary',
    sector: 'government',
    gender: 'girls',
    logoUrl: '/images/placeholders/school-9.jpg',
    lowestAnnualTuition: 0,
    highestAnnualTuition: 0,
    scholarshipAvailable: false,
    boardingAvailable: false,
    hasActiveApplicationTemplate: false,
    hasOpenCapacity: true,
    totalEnrolment: 950,
    internationalStudentPercentage: 5,
    religiousAffiliation: null,
    curriculumOffered: 'VCE',
    levelsOffered: 'secondary',
    yearLevelBands: ['secondary'],
    capacityBands: ['medium'],
    _geo: { lat: -37.8422, lng: 144.9688 },
    enrolmentStatus: 'closed',
    curriculumCodes: ['VCE'],
    accommodation: 'none',
    annualTuitionFrom: 5000,
    programTypes: ['australian-cert'],
    entryTerms: ['term1'],
    atarAvailable: true,
    englishLanguageSupport: false,
    englishTestMinScores: {},
  },
  {
    documentId: 'mock-010',
    name: 'Loreto Kirribilli',
    slug: 'loreto-kirribilli',
    state: 'NSW',
    suburb: 'Kirribilli',
    postcode: '2061',
    schoolType: 'combined',
    sector: 'catholic',
    gender: 'girls',
    logoUrl: '/images/placeholders/school-10.jpg',
    lowestAnnualTuition: 28000,
    highestAnnualTuition: 33000,
    scholarshipAvailable: true,
    boardingAvailable: true,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: true,
    totalEnrolment: 1100,
    internationalStudentPercentage: 9,
    religiousAffiliation: null,
    curriculumOffered: 'HSC',
    levelsOffered: 'combined',
    yearLevelBands: ['primary', 'secondary'],
    capacityBands: ['large'],
    _geo: { lat: -33.8474, lng: 151.2093 },
    enrolmentStatus: 'open',
    curriculumCodes: ['HSC'],
    accommodation: 'homestay',
    annualTuitionFrom: 28000,
    programTypes: ['australian-cert'],
    entryTerms: ['term1', 'term2'],
    atarAvailable: true,
    englishLanguageSupport: true,
    englishTestMinScores: { ielts: 5.5, idat: 50 },
  },
  {
    documentId: 'mock-011',
    name: 'Al Noori Muslim School',
    slug: 'al-noori-muslim-school',
    state: 'NSW',
    suburb: 'Greenacre',
    postcode: '2190',
    schoolType: 'combined',
    sector: 'non-government',
    gender: 'co-ed',
    logoUrl: '/images/placeholders/school-11.jpg',
    lowestAnnualTuition: 8000,
    highestAnnualTuition: 11000,
    scholarshipAvailable: false,
    boardingAvailable: false,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: true,
    totalEnrolment: 1050,
    internationalStudentPercentage: 4,
    religiousAffiliation: 'islamic',
    curriculumOffered: 'HSC',
    levelsOffered: 'combined',
    yearLevelBands: ['primary', 'secondary'],
    capacityBands: ['medium'],
    _geo: { lat: -33.9020, lng: 151.0586 },
    enrolmentStatus: 'limited',
    curriculumCodes: ['HSC'],
    accommodation: 'none',
    annualTuitionFrom: 8000,
    programTypes: ['australian-cert'],
    entryTerms: ['term1'],
    atarAvailable: true,
    englishLanguageSupport: true,
    englishTestMinScores: { ielts: 5.0 },
  },
  {
    documentId: 'mock-012',
    name: 'Geelong Grammar School',
    slug: 'geelong-grammar-school',
    state: 'VIC',
    suburb: 'Corio',
    postcode: '3214',
    schoolType: 'combined',
    sector: 'non-government',
    gender: 'co-ed',
    logoUrl: '/images/placeholders/school-12.jpg',
    lowestAnnualTuition: 55000,
    highestAnnualTuition: 65000,
    scholarshipAvailable: true,
    boardingAvailable: true,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: true,
    totalEnrolment: 1650,
    internationalStudentPercentage: 20,
    religiousAffiliation: 'anglican',
    curriculumOffered: 'VCE',
    levelsOffered: 'combined',
    yearLevelBands: ['primary', 'secondary'],
    capacityBands: ['large'],
    _geo: { lat: -38.0649, lng: 144.3545 },
    enrolmentStatus: 'open',
    curriculumCodes: ['VCE', 'IB'],
    accommodation: 'both',
    annualTuitionFrom: 62000,
    programTypes: ['australian-cert', 'ib'],
    entryTerms: ['term1', 'term2', 'term3'],
    atarAvailable: true,
    englishLanguageSupport: true,
    englishTestMinScores: { ielts: 6.0, pte: 50, cambridge: 169 },
  },
  {
    documentId: 'mock-013',
    name: 'The Scots College',
    slug: 'the-scots-college',
    state: 'NSW',
    suburb: 'Bellevue Hill',
    postcode: '2023',
    schoolType: 'combined',
    sector: 'non-government',
    gender: 'boys',
    logoUrl: '/images/placeholders/school-13.jpg',
    lowestAnnualTuition: 37000,
    highestAnnualTuition: 43000,
    scholarshipAvailable: true,
    boardingAvailable: true,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: true,
    totalEnrolment: 1500,
    internationalStudentPercentage: 13,
    religiousAffiliation: 'presbyterian',
    curriculumOffered: 'HSC',
    levelsOffered: 'combined',
    yearLevelBands: ['primary', 'secondary'],
    capacityBands: ['large'],
    _geo: { lat: -33.8847, lng: 151.2598 },
    enrolmentStatus: 'open',
    curriculumCodes: ['HSC'],
    accommodation: 'boarding',
    annualTuitionFrom: 37000,
    programTypes: ['australian-cert'],
    entryTerms: ['term1', 'term2'],
    atarAvailable: true,
    englishLanguageSupport: true,
    englishTestMinScores: { ielts: 5.5, pte: 46 },
  },
  {
    documentId: 'mock-014',
    name: 'Moriah College',
    slug: 'moriah-college',
    state: 'NSW',
    suburb: 'Queens Park',
    postcode: '2022',
    schoolType: 'combined',
    sector: 'non-government',
    gender: 'co-ed',
    logoUrl: '/images/placeholders/school-14.jpg',
    lowestAnnualTuition: 31000,
    highestAnnualTuition: 36000,
    scholarshipAvailable: false,
    boardingAvailable: false,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: true,
    totalEnrolment: 1600,
    internationalStudentPercentage: 7,
    religiousAffiliation: 'jewish',
    curriculumOffered: 'HSC',
    levelsOffered: 'combined',
    yearLevelBands: ['primary', 'secondary'],
    capacityBands: ['large'],
    _geo: { lat: -33.9034, lng: 151.2515 },
    enrolmentStatus: 'open',
    curriculumCodes: ['HSC'],
    accommodation: 'none',
    annualTuitionFrom: 31000,
    programTypes: ['australian-cert'],
    entryTerms: ['term1'],
    atarAvailable: true,
    englishLanguageSupport: false,
    englishTestMinScores: { ielts: 5.5 },
  },
  {
    documentId: 'mock-015',
    name: 'Brigidine College Randwick',
    slug: 'brigidine-college-randwick',
    state: 'NSW',
    suburb: 'Randwick',
    postcode: '2031',
    schoolType: 'secondary',
    sector: 'catholic',
    gender: 'girls',
    logoUrl: '/images/placeholders/school-15.jpg',
    lowestAnnualTuition: 15000,
    highestAnnualTuition: 18000,
    scholarshipAvailable: false,
    boardingAvailable: false,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: true,
    totalEnrolment: 700,
    internationalStudentPercentage: 4,
    religiousAffiliation: null,
    curriculumOffered: 'HSC',
    levelsOffered: 'secondary',
    yearLevelBands: ['secondary'],
    capacityBands: ['medium'],
    _geo: { lat: -33.9168, lng: 151.2411 },
    enrolmentStatus: 'open',
    curriculumCodes: ['HSC'],
    accommodation: 'none',
    annualTuitionFrom: 15000,
    programTypes: ['australian-cert'],
    entryTerms: ['term1', 'term2'],
    atarAvailable: true,
    englishLanguageSupport: false,
    englishTestMinScores: {},
  },
  {
    documentId: 'mock-016',
    name: 'Wesley College Perth',
    slug: 'wesley-college-perth',
    state: 'WA',
    suburb: 'South Perth',
    postcode: '6151',
    schoolType: 'combined',
    sector: 'non-government',
    gender: 'co-ed',
    logoUrl: '/images/placeholders/school-16.jpg',
    lowestAnnualTuition: 21000,
    highestAnnualTuition: 27000,
    scholarshipAvailable: true,
    boardingAvailable: true,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: false,
    totalEnrolment: 1250,
    internationalStudentPercentage: 11,
    religiousAffiliation: 'uniting-church',
    curriculumOffered: 'WACE',
    levelsOffered: 'combined',
    yearLevelBands: ['primary', 'secondary'],
    capacityBands: ['large'],
    _geo: { lat: -31.9740, lng: 115.8615 },
    enrolmentStatus: 'waitlist',
    curriculumCodes: ['WACE', 'IB'],
    accommodation: 'boarding',
    annualTuitionFrom: 21000,
    programTypes: ['australian-cert', 'ib'],
    entryTerms: ['term1', 'term2', 'term3'],
    atarAvailable: true,
    englishLanguageSupport: true,
    englishTestMinScores: { ielts: 5.5, aeas: 60 },
  },
  {
    documentId: 'mock-017',
    name: 'Scotch College Melbourne',
    slug: 'scotch-college-melbourne',
    state: 'VIC',
    suburb: 'Hawthorn',
    postcode: '3122',
    schoolType: 'combined',
    sector: 'non-government',
    gender: 'boys',
    logoUrl: '/images/placeholders/school-17.jpg',
    lowestAnnualTuition: 39000,
    highestAnnualTuition: 45000,
    scholarshipAvailable: true,
    boardingAvailable: true,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: true,
    totalEnrolment: 1700,
    internationalStudentPercentage: 16,
    religiousAffiliation: 'presbyterian',
    curriculumOffered: 'VCE',
    levelsOffered: 'combined',
    yearLevelBands: ['primary', 'secondary'],
    capacityBands: ['large'],
    _geo: { lat: -37.8238, lng: 145.0398 },
    enrolmentStatus: 'limited',
    curriculumCodes: ['VCE', 'IB'],
    accommodation: 'boarding',
    annualTuitionFrom: 39000,
    programTypes: ['australian-cert', 'ib'],
    entryTerms: ['term1'],
    atarAvailable: true,
    englishLanguageSupport: true,
    englishTestMinScores: { ielts: 6.0, pte: 55, cambridge: 169 },
  },
  {
    documentId: 'mock-018',
    name: 'Churchlands Senior High School',
    slug: 'churchlands-senior-high-school',
    state: 'WA',
    suburb: 'Churchlands',
    postcode: '6018',
    schoolType: 'secondary',
    sector: 'government',
    gender: 'co-ed',
    logoUrl: '/images/placeholders/school-18.jpg',
    lowestAnnualTuition: 0,
    highestAnnualTuition: 0,
    scholarshipAvailable: false,
    boardingAvailable: false,
    hasActiveApplicationTemplate: false,
    hasOpenCapacity: true,
    totalEnrolment: 1200,
    internationalStudentPercentage: 4,
    religiousAffiliation: null,
    curriculumOffered: 'WACE',
    levelsOffered: 'secondary',
    yearLevelBands: ['secondary'],
    capacityBands: ['large'],
    _geo: { lat: -31.9119, lng: 115.8040 },
    enrolmentStatus: 'open',
    curriculumCodes: ['WACE'],
    accommodation: 'none',
    annualTuitionFrom: 5000,
    programTypes: ['australian-cert'],
    entryTerms: ['term1', 'term2'],
    atarAvailable: true,
    englishLanguageSupport: false,
    englishTestMinScores: {},
  },
  {
    documentId: 'mock-019',
    name: 'Concordia College',
    slug: 'concordia-college',
    state: 'SA',
    suburb: 'Highgate',
    postcode: '5063',
    schoolType: 'combined',
    sector: 'non-government',
    gender: 'co-ed',
    logoUrl: '/images/placeholders/school-19.jpg',
    lowestAnnualTuition: 16000,
    highestAnnualTuition: 20000,
    scholarshipAvailable: false,
    boardingAvailable: false,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: true,
    totalEnrolment: 980,
    internationalStudentPercentage: 5,
    religiousAffiliation: 'lutheran',
    curriculumOffered: 'SACE',
    levelsOffered: 'combined',
    yearLevelBands: ['primary', 'secondary'],
    capacityBands: ['medium'],
    _geo: { lat: -34.9382, lng: 138.6257 },
    enrolmentStatus: 'open',
    curriculumCodes: ['SACE'],
    accommodation: 'none',
    annualTuitionFrom: 16000,
    programTypes: ['australian-cert'],
    entryTerms: ['term1', 'term3'],
    atarAvailable: true,
    englishLanguageSupport: false,
    englishTestMinScores: { ielts: 5.5 },
  },
  {
    documentId: 'mock-020',
    name: 'ELICOS Language Academy Melbourne',
    slug: 'elicos-language-academy-melbourne',
    state: 'VIC',
    suburb: 'Carlton',
    postcode: '3053',
    schoolType: 'secondary',
    sector: 'non-government',
    gender: 'co-ed',
    logoUrl: '/images/placeholders/school-20.jpg',
    lowestAnnualTuition: 9000,
    highestAnnualTuition: 12000,
    scholarshipAvailable: false,
    boardingAvailable: false,
    hasActiveApplicationTemplate: true,
    hasOpenCapacity: true,
    totalEnrolment: 350,
    internationalStudentPercentage: 95,
    religiousAffiliation: null,
    curriculumOffered: 'VCE',
    levelsOffered: 'secondary',
    yearLevelBands: ['secondary'],
    capacityBands: ['small'],
    _geo: { lat: -37.8000, lng: 144.9674 },
    enrolmentStatus: 'open',
    curriculumCodes: ['VCE'],
    accommodation: 'homestay',
    annualTuitionFrom: 9000,
    programTypes: ['elicos'],
    entryTerms: ['term1', 'term2', 'term3', 'term4'],
    atarAvailable: false,
    englishLanguageSupport: true,
    englishTestMinScores: { ielts: 4.0, duolingo: 75 },
  },
];
